name: Get Selected
icon: check-square
color: green
description:
  Returns a string with the name of the selected checkboxes on a
  workflow_dispatch event. Separator defaults to " "
author: joao-zanutto

inputs:
  ignore:
    description: List of options to ignore during assertion
    required: false
  separator:
    description: String used to separate each of the selected outputs
    required: false
    default: ' '

outputs:
  selected:
    description: Name of the selected checkboxes

runs:
  using: node20
  main: dist/index.js
